service: todoss-serverless-api
configValidationMode: error
useDotenv: true

package:
  individually: true

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: dev
  region: "us-east-1"
  timeout: 3
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  listTodo:
    handler: src/todos/list.handler
    events:
      - http:
          method: GET
          path: /todos/{userId}

  createTodo:
    handler: src/todos/create.handler
    events:
      - http:
          method: POST
          path: /todos/{userId}

resources:
  Resources:
    certificatesDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todos
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
